inherit_from:
  - _layout.yml
  - _metrics.yml
  - _rspec.yml
  - _style.yml

##
# Merge instead of overwriting. For more details, see:
# https://docs.rubocop.org/rubocop/configuration.html#merging-arrays-using-inherit_mode
#
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rake
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.0
