name: Test Suite

# Run against all commits and pull requests.
on: [ push, pull_request ]

jobs:
  styling:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundler-cache: true
    - name: Run rubocop
      run: bundle exec rake rubocop
